language: python
python:
  - "2.7"
  - "3.6"
os:
  - linux
install:
  - pip install --upgrade six
  - pip install .
  - pip install -r requirements/requirements.txt
script: pytest
branches:
  only:
    - dev
    - master
