site_name: Geofetch
site_url: http://code.databio.org/geofetch/
repo_url: http://github.com/pepkit/geofetch
site_logo: img/geofetch_logo_dark.svg
pypi_name: geofetch

nav:
  - Getting started:
    - Introduction: README.md
    - Tutorial: tutorial.md
  - How-to Guides:
    - How to specify multiple accessions: howto-limit.md
    - How to control data location: howto-location.md
  - Reference:
    - Usage: usage.md
    - API: autodoc_build/geofetch.md
    - FAQ: faq.md
    - Support: support.md
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio


plugins:
  - search
  - databio:
      usage_template: "docs/usage_template.md"
      usage_cmds:
        -"geofetch --help
