site_name: Geofetch
site_url: http://code.databio.org/geofetch/
repo_url: http://github.com/pepkit/geofetch
site_logo: img/geofetch_logo_dark.svg
pypi_name: geofetch

nav:
  - Getting started:
    - Introduction: README.md
    - Install and configure: install.md
    - SRA convert: sra_convert.md
  - Tutorials:
    - Tutorial for processed data: processed-data-downloading.md
    - Tutorial for raw data: raw-data-downloading.md
    - Python geofetch tutorial: python-usage.md
  - How-to Guides:
    - Specifying samples to download: file-specification.md
    - Set SRA data download location: howto-location.md
    - Download list of GSEs: how_to_get_gse.md
  - Reference:
    - Metadata output: metadata_output.md
    - Usage: usage.md
    - FAQ: faq.md
    - Support: http://github.com/pepkit/geofetch/issues
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio


plugins:
  - search
  - databio:
      jupyter_source: "docs_jupyter"
      jupyter_build: "docs_jupyter/build"
      usage_template: "docs/usage_template.md"
      usage_cmds:
        -"geofetch --help
